### ISSUE TITLE
Add a style theme

### ISSUE THREAD

**Issue by Vehmloewff** [svelte-toolbox/svelte-toolbox#105]
I am not sure exactly what to call this, but I think that "Style Theme" sounds good.

It's just a set of CSS vars in `global.css` that look like this:

```css
:root {
	--back: #ffffff;
	--back-light: #f6fafd;
	--back-api: #eff8ff;
	--prime: #98603d;
	--second: #434346;
	--flash: #40b3ff;
	--heading: var(--second);
	--text: #444;
	--sidebar-text: rgba(255, 255, 255, 0.75);
	--border-w: 0.3rem;
	--border-r: 0.4rem;
}
```

Then all the other vars would be set to those variables.

Yeah, more vars such as `--prime-t-10` (`--prime` transparent 10%) would probably be needed, but for the most part I think this would work.

Notice any problems with this idea?  Have a comment?

Drop it below.
