### ISSUE TITLE
Style bug with UIInput

### ISSUE THREAD

**Issue by Vehmloewff** [svelte-toolbox/svelte-toolbox#26]
As seen in this [REPL](https://svelte.dev/repl/10d2e043781845018617c89676025437?version=3.6.5), the input has an extra margin on the bottom.

As this is just the default Svelte REPL styles, it can be overridden with the following css:
```css
input, button, select, textarea {
    margin: 0;
}
```

But that is just a pain to do every time.
